export const DAILY_TIPS = [
  { icon: "🎣", cat: "Hook-Strategie",      tip: "Die ersten 3 Wörter deiner Caption entscheiden ob jemand 'mehr lesen' klickt. Teste heute: 'Niemand redet darüber:', 'Ich hätte nie gedacht:' oder eine direkte Frage." },
  { icon: "💾", cat: "Algorithmus",         tip: "Speichere-Rate schlägt Likes. Instagram zeigt Content öfter wenn er bookmarkt wird. Erstelle heute 'Must-Save-Content' — Listen, Checklisten, How-Tos." },
  { icon: "#️⃣", cat: "Hashtag-Mix",         tip: "Mixe immer 3 Größenklassen: 5 Nischen-Hashtags (unter 50k Posts), 15 mittlere (50k–500k) und 5 breite (über 500k). Nischen bringen Follower, Breite bringt Reichweite." },
  { icon: "♻️", cat: "Repurposing",         tip: "1 Karussell = 7 Formate: Blog-Artikel, 7 Einzelposts für Stories, Newsletter-Teaser, Pinterest-Pin, Reel-Skript, LinkedIn-Post. Erstelle einmal, veröffentliche überall." },
  { icon: "💬", cat: "Community",           tip: "Antworte in den ersten 60 Minuten nach dem Post auf JEDEN Kommentar. Das signalisiert Instagram Aktivität und pusht den Beitrag an mehr Menschen." },
  { icon: "📖", cat: "Storytelling",        tip: "Menschen folgen Menschen, nicht Themen. Starte deinen nächsten Post mit 'Vor 3 Jahren...' oder 'Ich war 25 und hatte keine Ahnung...' — persönliche Geschichten bauen Vertrauen." },
  { icon: "📌", cat: "Pinterest SEO",       tip: "Pinterest ist eine Suchmaschine, kein Social Network. Dein Pin-Titel braucht Keywords die deine Zielgruppe wirklich tippt — denk wie Google, nicht wie Instagram." },
  { icon: "📧", cat: "Newsletter",          tip: "Deine E-Mail-Liste gehört dir — Instagram-Follower nicht. Erwähne deinen Newsletter heute in einer Story oder im Caption-Text und erkläre warum sich das Abo lohnt." },
  { icon: "🎯", cat: "Zielgruppe",          tip: "Schreibe deine nächste Caption als Brief an eine einzige Person: Deine ideale Followerin. Je spezifischer du bist, desto mehr fühlen sich alle angesprochen." },
  { icon: "🧪", cat: "Testing",             tip: "Poste ähnlichen Content an verschiedenen Tagen/Uhrzeiten und tracke was besser performt. Die beste Posting-Zeit ist individuell — finde deine durch Experimente." },
  { icon: "🌱", cat: "Konsistenz",          tip: "Perfekter Content der nie erscheint bringt dir nichts. Guter Content der regelmäßig erscheint schlägt perfekten Content der selten kommt — jedes Mal." },
  { icon: "🔍", cat: "Research",            tip: "Schau dir heute die Kommentare unter großen Accounts in deiner Nische an. Die Fragen die dort gestellt werden sind deine besten Content-Ideen." },
  { icon: "📸", cat: "Visuelles",           tip: "Dein Feed-Bild muss im 3-Sekunden-Scroll auffallen. Weniger ist mehr: 1 starkes Bild, 1 klarer Text-Hook, 1 Farbe die zu deinem Branding passt." },
  { icon: "🤝", cat: "Kooperationen",       tip: "Micro-Influencer (1k–10k Follower) haben oft bessere Engagement-Raten als große Accounts. Für Marken bist du als authentische Nischen-Expertin wertvoller als du denkst." },
  { icon: "💡", cat: "Content-Ideen",       tip: "Scrolle durch deine ältesten Posts von vor 1+ Jahr. Welche Themen waren damals gut? Bring sie als 'Update 2025' neu raus — deine neuen Follower haben das nicht gesehen." },
  { icon: "⏰", cat: "Planung",             tip: "Batch-Produktionstag: Reserviere 2–3 Stunden pro Woche um 5–7 Posts auf einmal zu erstellen. Das ist effektiver als jeden Tag 30 Minuten und nimmt den Druck raus." },
  { icon: "🎪", cat: "Karussell-Struktur",  tip: "Karussell-Formel: Slide 1 = Hook (warum soll ich weiterswipen?), Slides 2–6 = Wert, Slide 7 = Zusammenfassung, Slide 8 = CTA. Diese Struktur funktioniert in jeder Nische." },
  { icon: "🌊", cat: "Trends",              tip: "Sei früh dran: Wenn ein Trend gerade anfängt in Europa anzukommen, hast du 2–4 Wochen Vorsprung. Beobachte was in den USA gerade groß wird." },
  { icon: "🧠", cat: "Mindset",             tip: "Vergleiche dich nie mit Accounts die 5 Jahre Vorsprung haben. Vergleiche dich mit dir selbst vor 3 Monaten — das ist der einzige Vergleich der zählt." },
  { icon: "📊", cat: "Analytics",           tip: "Der wichtigste Wert ist nicht Follower — es ist die Engagement-Rate. 500 engaged Follower sind mehr wert als 5.000 die nie interagieren." },
  { icon: "✨", cat: "Authentizität",        tip: "Deine 'Schwäche' ist deine Stärke. Was du an dir selbst nicht magst — Ehrlichkeit darüber resoniert tiefer als jeder perfekte Motivations-Post." },
  { icon: "🛍️", cat: "Monetarisierung",     tip: "Dein erstes Produkt muss nicht perfekt sein — es muss existieren. Ein 9€ PDF-Guide mit echtem Mehrwert ist besser als ein 97€ Kurs der nie fertig wird." },
  { icon: "📱", cat: "Reels",               tip: "Die ersten 3 Sekunden eines Reels entscheiden über alles. Kein Intro, keine Begrüßung, kein Logo — komm sofort zum Punkt und liefere den Hook." },
  { icon: "🗺️", cat: "Content-Strategie",   tip: "90% Mehrwert, 10% Promotion. Wenn du 9 Posts hilfst und 1 etwas verkaufst, fühlt es sich für niemanden nach Werbung an." },
  { icon: "💪", cat: "Motivation",          tip: "Du brauchst keine 10.000 Follower um anzufangen. Die ersten 100 treuen Follower sind mehr wert als 10.000 zufällige. Baue auf Qualität, nicht Quantität." },
  { icon: "🌙", cat: "Burnout-Prävention",  tip: "Plane jeden Monat mindestens 1 'Content-freien' Tag ein. Ausgebrannte Creator produzieren schlechten Content — Pause ist Teil der Strategie, nicht ihr Feind." },
  { icon: "🎨", cat: "Branding",            tip: "Nutze maximal 3 Farben, 2 Schriften und 1 Tone-of-Voice konsequent überall. Wiedererkennbarkeit entsteht durch Konsistenz, nicht durch perfektes Design." },
  { icon: "🤲", cat: "Community aufbauen",  tip: "Stelle am Ende jedes Posts EINE konkrete Frage die man in 1 Satz beantworten kann. 'Was ist dein Liebling-Morgenritual?' bekommt mehr Antworten als 'Was denkst du?'" },
];
